spring:
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: always
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: bank
account:
  transactions:
    topic: account-transactions